services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --default-time-zone='+00:00'
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "${DATABASE_USER}", "-p${DATABASE_PASSWORD}", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - TZ=UTC
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: sh -c "service cron start && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data: